### ISSUE TITLE
Strange characters in coverflow

### ISSUE THREAD

**Issue by hagud** [bywatersolutions/koha-plugin-coverflow#1]
We have implemented coverflow plugin into a koha 3.22.5 on debian 8 installed by packachges, standar configuration of apache.., mysql

We have congigured the file and point to the coverflow to report 9, with right character codification... but on the opac it shows wrong the title link to the bib record
screen shot of the report
![captura de pantalla 2016-03-31 a las 14 58 58](https://cloud.githubusercontent.com/assets/18190276/14176406/1dbff138-f751-11e5-95a1-efab83cda43c.png)

![captura de pantalla 2016-03-31 a las 14 56 46](https://cloud.githubusercontent.com/assets/18190276/14176347/d230bd6a-f750-11e5-9198-4eb2b7e5a43c.png)

thanks in advance

**Comment by WNickC** [comment]
Kyle had previously pushed a patch for this, I issued a new release.  You can upload the new version in place and it should fix the issue.

Thanks!
