### ISSUE TITLE
Incompatible with Koha Community 17.11

### ISSUE THREAD

**Issue by scoenye** [bywatersolutions/koha-plugin-coverflow#12]
The template loading code of KC 17.11 was changed to reject parent path access attempts. This plugin now triggers a "bad template path" exception when the report.tt template is loaded. As a result, the coverflow widget does not make it to the browser.

The root cause is the following code in Coverflow/coverflow.pl:
`use FindBin;                 # locate this script`
`use lib "$FindBin::Bin/../../../../../"; # use the parent directory`
The /../../../../../ string is injected in the template lookup path, triggering the rejection.

Replacing the above two lines with the code below makes the plugin operational again:
`use C4::Context;`
`use lib C4::Context->config("pluginsdir");`

**Comment by WNickC** [comment]
Thanks for the tip, code pushed today :-)
