### ISSUE TITLE
Coverflow not working in koha 18.05.04

### ISSUE THREAD

**Issue by PSMCHSLibrary** [bywatersolutions/koha-plugin-coverflow#14]
I tried with editing below suggestion from your previous post and suggestions

my $template = $self->get_template( { file => File::Spec->rel2abs('report.tt') } );

The root cause is the following code in Coverflow/coverflow.pl:
use FindBin; # locate this script
use lib "$FindBin::Bin/../../../../../"; # use the parent directory
The /../../../../../ string is injected in the template lookup path, triggering the rejection.

Replacing the above two lines with the code below makes the plugin operational again:
use C4::Context;
use lib C4::Context->config("pluginsdir");

CoverFlow.pm fails to compile

Reference to
use C4::Branch;

which is no longer required (and can be removed)

and

use Koha::Caches;
to replace
use Koha::Cache;

Only one occurrence of this in the CoverFlow.pm

my $cache = Koha::Cache->get_instance();
becomes
my $cache = Koha::Caches->get_instance();
When I try to run the report in coverflow plugin getting this error:
There is no such report.

For help, please send mail to the webmaster ([no address given]), giving this error message and the time and date of the error. 
Report has been created and tested its working..
Please suggest me how fix and run

**Comment by kidclamp** [comment]
The reference code has been updated and coverflow should work in 18.05
