### ISSUE TITLE
Coverflow not longer works in koha 18.11

### ISSUE THREAD

**Issue by audhep** [bywatersolutions/koha-plugin-coverflow#16]
I guys,
I've upgraded to the latest koha release and I made many test:
ubuntu 16.04 + koha 17.11.12 + coverflow 2.4.24 perfect!
ubuntu 16.04 + koha 18.05.04 + coverflow 2.4.24 at last seemed to be ok
ubuntu 16.04 + koha 18.11.00 + coverflow 2.4.24 doesn't work at all
either
ubuntu 18.04.01 + koha 17.11.12 + coverflow 2.4.24 perfect!
ubuntu 18.04.01 + koha 18.05.04 + coverflow 2.4.24 at last seemed to be ok
ubuntu 18.04.01 + koha 18.11.00 + coverflow 2.4.24 doesn't work at all!

any hint?
Thanks

**Comment by kidclamp** [comment]
Please test the latest version, it should work now

**Comment by audhep** [comment]
I will try!!! many thanks!
