### ISSUE TITLE
Js code is not generating

### ISSUE THREAD

**Issue by ChristinaEJ** [bywatersolutions/koha-plugin-coverflow#18]
I'm using Koha 18.11 and i'm not getting any autogenerated code in OpacUserJS after updating the plugin with a report id (as shown in the setup guide).

**Comment by kidclamp** [comment]
I suspect we need to update the documentation. The plugin will no longer add code to the system preferences, however, it should automatically insert the needed javascript into any opac pages.

**Comment by ChristinaEJ** [comment]
Ahh then my issue is the auto generated code doesn't match up with the location. The code generated states "/**plugin**/Koha/Plugin/Com...." and the actual location is "/**plugins**/Koha/Plugin/Com...."
