### ISSUE TITLE
Problem display book covers from all branches

### ISSUE THREAD

**Issue by vimal0212** [bywatersolutions/koha-plugin-coverflow#23]
We are using the plugin version 2.4.29.
We have three library branches. It display books from one branch.
It does not display book covers from two other branches.
Here is the url of our out OPAC,
[http://koha.riemysore.ac.in/cgi-bin/koha/opac-main.pl](url)

**Comment by kidclamp** [comment]
Can you clarify with a link that works versus one that doesn't? Or add a link to titles that don't show properly?

When you say other branches don't display, do that have blank covers, or the books don't appear in the coverflow?
