### ISSUE TITLE
What version of coverflow are supported in which versions of Koha?

### ISSUE THREAD

**Issue by minusdavid** [bywatersolutions/koha-plugin-coverflow#29]
It's not clear what versions of coverflow are supported in which versions of Koha.

**Comment by kidclamp** [comment]
That is true, we have discussed moving to branches for each version but have not yet
The versions before most recent should work with most pre-19.05.08 - the api patches require 19.05.08 plus (static files via api)

Not closing, but did want to at least semi-answer

**Comment by minusdavid** [comment]
Yeah the most recent version should be labeled as "DONOTUSE" or something, as it was definitely the wrong thing to use too...

I tried downgrading but the metadata in the database is wrong. I might just try to hack that... that's probably just a flaw in the whole plugin system though

**Comment by kidclamp** [comment]
What version of Koha and what version of Coverflow? What is the problem that you are seeing?

The most recent version works with 19.05.08 and above, and should work fine with those

**Comment by minusdavid** [comment]
Oops meant to reply to this much earlier.

It was 19.11.05 and the latest version of Coverflow. It seemed to just "not work".

But I suspect after more experimentation with my own plugin developments, that I probably needed to restart Plack, and that it probably would've worked then.

**Comment by minusdavid** [comment]
Which I guess is a usability issue because how does a library administrator install a plugin and then restart Plack... but another issue for another day.

**Comment by minusdavid** [comment]
> Oops meant to reply to this much earlier.
> 
> It was 19.11.05 and the latest version of Coverflow. It seemed to just "not work".
> 
> But I suspect after more experimentation with my own plugin developments, that I probably needed to restart Plack, and that it probably would've worked then.

Yeah, it was a case where I needed to restart the Plack so that the injected API route was detected. Much better now.

**Comment by tomascohen** [comment]
Cool
