### ISSUE TITLE
CoverFlow 2.3

### ISSUE THREAD

**Issue by hagud** [bywatersolutions/koha-plugin-coverflow#3]
Good morning

we have downloaded the coverflow plugin 2.3.kpz, but when we try to uncompress from koha, we get this error message

Unable to unzip '/tmp/GkOj5g15YP.3.kpz':  at /usr/share/koha/intranet/cgi-bin/plugins/plugins-upload.pl line 83.
Extract failed due to errors at /usr/share/koha/intranet/cgi-bin/plugins/plugins-upload.pl line 83.
ERROR: Extraction of '.git/objects/08/6ed32d3280ac3d7fbe9067ba3760cf1843b97f' from '/tmp/GkOj5g15YP.3.kpz' failed

We are able to upload older versions

Thanks you for this plugin

**Comment by WNickC** [comment]
This should be fixed now, it was an error in the zip I attached, just grabbed the wrong one :-)
