### ISSUE TITLE
Version 2.4.29 triggering error in browser console

### ISSUE THREAD

**Issue by minusdavid** [bywatersolutions/koha-plugin-coverflow#30]
jquery-3.4.1.min_19.1105000.js:2 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

**Comment by minusdavid** [comment]
Looks like a possible issue in the flipster library

**Comment by tomascohen** [comment]
This is soo first quarter... :-D Please reopen if it is still present in current versions.
