### ISSUE TITLE
Latest version 2.4.35 seems to have some issue related to missing file

### ISSUE THREAD

**Issue by mishravk79** [bywatersolutions/koha-plugin-coverflow#32]
In .kpz file some script files are missing hence automated scripts are not generate and stored in opacuserjs/opacusercss. I installed and compared with old. However olds are not working on latest Koha 20.05.

**Comment by kidclamp** [comment]
Can you describe the errors you are seeing and the files missing?

**Comment by mishravk79** [comment]
Hi

When I installed the latest version coverflow.pl file and many more is
missing from /var/lib/koha/library/plugin..... and after uploading and
configuring the plugin auto generated codes in opacuserjs and opacusercss
does not appear.

But i have tried with old versions and there is no file missing and
autocode is generated still i cant able to get my coverflow on OPAC.

I tried all above on Koha 20.05.01 with debian buster.

The sige of plugin at github is very less in comparison to previous
versions you may check this. Sorry if i am not updated about anything.

With Regards,

Vinod Kumar Mishra,
Assistant Librarian,
Biju Patnaik Central Library (BPCL),
NIT Rourkela,
Sundergadh-769008,
Odisha,
India.
Mob:91+9439420860
ORCID ID: http://orcid.org/0000-0003-4666-7874

*"Spiritual relationship is far more precious than physical. Physical
relationship divorced from spiritual is body without soul" -- Mahatma
Gandhi*

**Comment by kidclamp** [comment]
Same as issue #33
