### ISSUE TITLE
Example localcover report still uses biblioimages instead of cover_images table

### ISSUE THREAD

**Issue by minusdavid** [bywatersolutions/koha-plugin-coverflow#46]
Koha has replaced biblioimages, so the example localcover report  provided with the plugin doesn't work for newer versions of Koha.

**Comment by tj-cks** [comment]
@minusdavid You can use the new cover_images table in your SQL to access your images.

**Comment by minusdavid** [comment]
> @minusdavid You can use the new cover_images table in your SQL to access your images.

Thanks. I'm familiar with the Koha database schema, but I imagine many people downloading the plugin won't be, so just pointing out the example should be updated. Something like this perhaps:

SELECT DISTINCT biblio.title, biblio.biblionumber,  SUBSTRING_INDEX(biblioitems.isbn, ' ', 1) AS isbn, c.imagenumber AS localcover
FROM items
LEFT JOIN biblioitems USING (biblioitemnumber) 
LEFT JOIN biblio ON (items.biblionumber=biblio.biblionumber)
LEFT JOIN cover_images c ON (items.biblionumber=c.biblionumber)
WHERE biblioitems.isbn IS NOT NULL AND biblioitems.isbn !=''
ORDER  BY RAND()
LIMIT  15;
