### ISSUE TITLE
no image lost 

### ISSUE THREAD

**Issue by hagud** [bywatersolutions/koha-plugin-coverflow#5]
Hi

We have identifier that with the new version, if you have a new record in the carroussel that have not isbn (the new feature) but have not localcover, doesn't publish the no image picture.

for isbn records that has no localcver or amazon... appears the no image default
for no isbn records that has no localcover , it doesn't appear anything

thanks for this plugin

**Comment by kidclamp** [comment]
titles with no isbn or localcover are now passed through as 'No image'
