### ISSUE TITLE
Coverflow no longer works in 17.05

### ISSUE THREAD

**Issue by jonathanfield** [bywatersolutions/koha-plugin-coverflow#7]
CoverFlow.pm fails to compile

Reference to
use C4::Branch;

which is no longer required (and can be removed)

and

use Koha::Caches;
to replace
use Koha::Cache;

Only one occurrence of this in the CoverFlow.pm

my $cache        = Koha::Cache->get_instance();
becomes
my $cache        = Koha::Caches->get_instance();

With these three small changes all working again.

**Comment by kidclamp** [comment]
These changes have been made
