### ISSUE TITLE
Coverflow not working

### ISSUE THREAD

**Issue by ilobweb** [bywatersolutions/koha-plugin-coverflow#8]
From Koha/Plugin/Com/ByWaterSolutions/CoverFlow.pm

    232     my $report_rec = get_saved_report(
    233         $report_name ? { 'name' => $report_name } : { 'id' => $report_id } );
    234     if ( !$report_rec ) { die "There is no such report.\n"; }

Coverflow configuration:

    - id: 2
      selector: #coverflow
      options:
           style: 'carousel'

Run this report:

    SELECT id, savedsql, report_name from saved_sql where id=2

When I am clicking 'Run Report' for the plugin, its giving 'No such report' error.

Here are the details : -
Koha version : 17.05

Report is public (id = 2) and executes following query : 
SELECT b.biblionumber, SUBSTRING_INDEX(m.isbn, ' ', 1) AS isbn, b.title
FROM items i
LEFT JOIN biblioitems m USING (biblioitemnumber)
LEFT JOIN biblio b ON (i.biblionumber=b.biblionumber)
WHERE DATE_SUB(CURDATE(),INTERVAL 30 DAY) <= i.dateaccessioned AND m.isbn IS NOT NULL AND m.isbn != ''
ORDER BY rand()
LIMIT 10

When I run this report, it returns 10 rows as expected.

Configuration in coverflow plugin: 
- id: 2
  selector: #coverflow
  options:
       style: coverflow

Added following lines in /etc/apache2/sites-available/myKohaInstance.conf before the </VirtualHost> tag for OPAC : - 
ScriptAlias /coverflow.pl "/var/lib/koha/mykoha/plugins/Koha/Plugin/Com/ByWaterSolutions/CoverFlow/coverflow.pl"
Alias /plugin "/var/lib/koha/mykoha/plugins"
# The stanza below is needed for Apache 2.4+
<Directory /var/lib/koha/mykoha/plugins>
      Options Indexes FollowSymLinks
      AllowOverride None
      Require all granted
</Directory>

JS code is generated in OPACUserJS. 

I am getting following log messages-

[Tue Aug 15 15:44:51.839806 2017] [cgi:error] [pid 20197] [client 137.122.64.13:29994] AH01215: [Tue Aug 15 15:44:51 2017] run.pl: CGI::param called in list context from /var/lib/koha/ilob-olbi/plugins/Koha/Plugin/Com/ByWaterSolutions/CoverFlow.pm line 129, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/share/perl5/CGI.pm line 405.: /usr/share/koha/intranet/cgi-bin/plugins/run.pl, referer: http://ilob-olbi-intra.juliencouturecentre.ca:8888/cgi-bin/koha/plugins/run.pl?class=Koha::Plugin::Com::ByWaterSolutions::CoverFlow&method=configure
[Tue Aug 15 15:44:58.598729 2017] [cgi:error] [pid 20197] [client 137.122.64.13:29994] AH01215: [Tue Aug 15 15:44:58 2017] run.pl: Use of uninitialized value in string eq at /usr/share/koha/lib/C4/Reports/Guided.pm line 709.: /usr/share/koha/intranet/cgi-bin/plugins/run.pl, referer: http://ilob-olbi-intra.juliencouturecentre.ca:8888/cgi-bin/koha/plugins/plugins-home.pl
[Tue Aug 15 15:44:58.599032 2017] [cgi:error] [pid 20197] [client 137.122.64.13:29994] AH01215: [Tue Aug 15 15:44:58 2017] run.pl: There is no such report.: /usr/share/koha/intranet/cgi-bin/plugins/run.pl, referer: http://ilob-olbi-intra.juliencouturecentre.ca:8888/cgi-bin/koha/plugins/plugins-home.pl
[Tue Aug 15 15:46:12.031165 2017] [cgi:error] [pid 20306] [client 137.122.64.13:30037] AH01215: [Tue Aug 15 15:46:12 2017] run.pl: CGI::param called in list context from /var/lib/koha/ilob-olbi/plugins/Koha/Plugin/Com/ByWaterSolutions/CoverFlow.pm line 129, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/share/perl5/CGI.pm line 405.: /usr/share/koha/intranet/cgi-bin/plugins/run.pl, referer: http://ilob-olbi-intra.juliencouturecentre.ca:8888/cgi-bin/koha/plugins/run.pl?class=Koha::Plugin::Com::ByWaterSolutions::CoverFlow&method=configure
[Tue Aug 15 15:46:34.131527 2017] [cgi:error] [pid 20314] [client 137.122.64.13:30063] AH01215: [Tue Aug 15 15:46:34 2017] run.pl: CGI::param called in list context from /var/lib/koha/ilob-olbi/plugins/Koha/Plugin/Com/ByWaterSolutions/CoverFlow.pm line 129, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/share/perl5/CGI.pm line 405.: /usr/share/koha/intranet/cgi-bin/plugins/run.pl, referer: http://ilob-olbi-intra.juliencouturecentre.ca:8888/cgi-bin/koha/plugins/run.pl?class=Koha::Plugin::Com::ByWaterSolutions::CoverFlow&method=configure
[Tue Aug 15 15:46:39.902866 2017] [cgi:error] [pid 20314] [client 137.122.64.13:30063] AH01215: [Tue Aug 15 15:46:39 2017] run.pl: Use of uninitialized value in string eq at /usr/share/koha/lib/C4/Reports/Guided.pm line 709.: /usr/share/koha/intranet/cgi-bin/plugins/run.pl, referer: http://ilob-olbi-intra.juliencouturecentre.ca:8888/cgi-bin/koha/plugins/plugins-home.pl
[Tue Aug 15 15:46:39.903293 2017] [cgi:error] [pid 20314] [client 137.122.64.13:30063] AH01215: [Tue Aug 15 15:46:39 2017] run.pl: There is no such report.: /usr/share/koha/intranet/cgi-bin/plugins/run.pl, referer: http://ilob-olbi-intra.juliencouturecentre.ca:8888/cgi-bin/koha/plugins/plugins-home.pl

**Comment by kidclamp** [comment]
The 'Run report' option for the plugin didn't actually work. It was there to define the plugin as a 'Report plugin' - I moved this - you will now have to find the plugin under 'All plugins' or via Admin->Manage plugins, but you won't have a broken button anymore
